import type { ModelAbilities, ModelCatalogEntry } from '../types'

const TEXT_VISION_TOOLS: ModelAbilities = {
  tools: 'supported',
  vision: 'supported',
  video: 'unsupported',
  reasoning: 'unsupported',
  fileInput: 'supported',
  imageOutput: 'unsupported',
}

const REASONING_MODEL: ModelAbilities = {
  ...TEXT_VISION_TOOLS,
  reasoning: 'supported',
}

export const OPENAI_MODELS: ModelCatalogEntry[] = [
  {
    provider: 'openai',
    id: 'gpt-5.2',
    displayName: 'GPT-5.2',
    aliases: ['gpt 5.2'],
    contextWindowTokens: 400000,
    abilities: REASONING_MODEL,
    iconKey: 'openai',
    source: 'builtin',
    catalogUpdatedAt: '2026-05-30',
  },
  {
    provider: 'openai',
    id: 'gpt-5',
    displayName: 'GPT-5',
    aliases: ['gpt 5'],
    contextWindowTokens: 400000,
    abilities: REASONING_MODEL,
    iconKey: 'openai',
    source: 'builtin',
    catalogUpdatedAt: '2026-05-30',
  },
  {
    provider: 'openai',
    id: 'gpt-4.1',
    displayName: 'GPT-4.1',
    aliases: ['gpt 4.1'],
    contextWindowTokens: 1047576,
    maxOutputTokens: 32768,
    abilities: TEXT_VISION_TOOLS,
    pricing: {
      inputPerMillionUsd: 2,
      outputPerMillionUsd: 8,
      cacheReadPerMillionUsd: 0.5,
    },
    iconKey: 'openai',
    source: 'builtin',
    catalogUpdatedAt: '2026-05-30',
  },
  {
    provider: 'openai',
    id: 'gpt-4o',
    displayName: 'GPT-4o',
    aliases: ['gpt 4o'],
    contextWindowTokens: 128000,
    maxOutputTokens: 16384,
    abilities: TEXT_VISION_TOOLS,
    pricing: {
      inputPerMillionUsd: 2.5,
      outputPerMillionUsd: 10,
      cacheReadPerMillionUsd: 1.25,
    },
    iconKey: 'openai',
    source: 'builtin',
    catalogUpdatedAt: '2026-05-30',
  },
  {
    provider: 'openai',
    id: 'gpt-4o-mini',
    displayName: 'GPT-4o mini',
    aliases: ['gpt 4o mini'],
    contextWindowTokens: 128000,
    maxOutputTokens: 16384,
    abilities: TEXT_VISION_TOOLS,
    pricing: {
      inputPerMillionUsd: 0.15,
      outputPerMillionUsd: 0.6,
      cacheReadPerMillionUsd: 0.075,
    },
    iconKey: 'openai',
    source: 'builtin',
    catalogUpdatedAt: '2026-05-30',
  },
  {
    provider: 'openai',
    id: 'o3',
    displayName: 'o3',
    contextWindowTokens: 200000,
    abilities: REASONING_MODEL,
    iconKey: 'openai',
    source: 'builtin',
    catalogUpdatedAt: '2026-05-30',
  },
  {
    provider: 'openai',
    id: 'o4-mini',
    displayName: 'o4-mini',
    contextWindowTokens: 200000,
    abilities: REASONING_MODEL,
    iconKey: 'openai',
    source: 'builtin',
    catalogUpdatedAt: '2026-05-30',
  },
]
